name: BlackBE
main: xyz.blackbe.blackbeplugin.BlackBEMain
version: "1.3.0"
api: ["1.0.0"]
load: POSTWORLD
authors: ["LixWorth", "darker"]
description: BlackBE NK Plugin blacbe.xyz
website: https://github.com/lixworth/BlackBE-NKPlugin

permissions:
  blackbe.command.default:
    description: BlackBE 云黑插件权限
    default: op