name: BlackBE
main: icu.cattery.lixworth.blackbe.BlackBE
version: "1.1"
api: ["1.0.5"]
load: POSTWORLD
author: LixWorth
description: BlackBE NK Plugin blacbe.xyz
website: https://github.com/lixworth/BlackBE-NKPlugin

commands:
  blackbe:
    description: BlackBE 云黑插件
    usage: "/blackbe"